[package]
name = "yarik-games"
version = "0.1.0"
edition = "2024"

[dependencies]
wgame = { path = "wgame/wgame" }
futures = "0.3.31"
rand = { version = "0.9.2", default-features = false, features = [
    "alloc",
    "small_rng",
] }
rand_distr = { version = "0.5.1", default-features = false }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tobj = { version = "4.0.3", default-features = false }
anyhow = "1.0.100"
derive_more = { version = "2.0.1", features = ["full"] }
defer = "0.2.1"
itertools = "0.14.0"
glam = { version = "0.30.9", features = ["serde", "rand"] }
euclid = "0.22.11"
metaphysics = "0.1.0"

[dev-dependencies]
approx = "0.5.1"
